save-period: 600
# Default reasons available when report
reasons:
  - Harassment
  - Offensive Profile
  - Spamming Advertisements
  - Suspected Cheater/Hacker
  - Impersonating another player
# This will allow players to report with their own reasons.
allow-custom-reason: true

custom-reason-min-length: 4

custom-reason-max-length: 20

allow-reporting-ops: false

allow-reporting-banned-players: false

# Plugin will check for new version from Github
check-update: true